"""create ingestion run

Revision ID: 2ae610ff28cd
Revises: fe71aac9b2ed
Create Date: 2026-09-11 11:49:54.487696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ae610ff28cd"
down_revision: str | Sequence[str] | None = "fe71aac9b2ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("dataset", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_downloaded", sa.Integer(), nullable=True),
        sa.Column("rows_inserted", sa.Integer(), nullable=True),
        sa.Column("rows_updated", sa.Integer(), nullable=True),
        sa.Column("rows_rejected", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_run")),
        schema="audit",
    )
    op.create_index(
        op.f("ix_ingestion_run_dataset"), "ingestion_run", ["dataset"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_ingestion_run_source"), "ingestion_run", ["source"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_ingestion_run_status"), "ingestion_run", ["status"], unique=False, schema="audit"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_run_status"), table_name="ingestion_run", schema="audit")
    op.drop_index(op.f("ix_ingestion_run_source"), table_name="ingestion_run", schema="audit")
    op.drop_index(op.f("ix_ingestion_run_dataset"), table_name="ingestion_run", schema="audit")
    op.drop_table("ingestion_run", schema="audit")
    # ### end Alembic commands ###
